version: '3'
services:

  client:
    container_name: react-redux-todolist
    expose:
      - 8001
    ports:
      - 8001:8001
    volumes:
      - ./packages/react-todolist:/opt/app
    build:
      context: ./packages/react-todolist
    command: npm run start

  database:
    container_name: react-redux-todolist-db
    image: postgres
    volumes:
      - ./packages/database:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=todolist
      - POSTGRES_DB=todolist
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: always
